#!/bin/bash

set -o errexit
set -x

root=$(dirname "$0")
cd "$root"

source ./goenv/activate

project_name=go-snake
project_parent=github.com/edudobay
project=$project_parent/$project_name

mkdir -p goenv/src/$project_parent
[[ -h goenv/src/$project && "$(realpath goenv/src/$project)" == "$(realpath .)" ]] || \
    ln -s $(realpath --relative-to=goenv/src/$project_parent .) goenv/src/$project

go get github.com/edudobay/go-snake
go build -o go-snake
